project:
  type: website
  output-dir: docs

website:
  title: "Quant Insights"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: flatly
    css: styles.css
    linestretch: 1.7

    grid:
        sidebar-width: 200px
        body-width: 1100px
        margin-width: 200px
        gutter-width: 1.5rem



